- project:
    name: openstack/mistral-extra
    templates:
      - merge-check
      - openstack-python-jobs
      - openstack-python35-jobs
      - check-requirements
    pre-release:
      jobs:
        - publish-openstack-python-tarball:
            dependencies:
              - publish-openstack-python-tarball
        - legacy-announce-release:
            dependencies:
              - legacy-pypi-both-upload
        - legacy-propose-update-constraints:
            dependencies:
              - legacy-pypi-both-upload
        - legacy-pypi-both-upload:
            dependencies:
              - publish-openstack-python-tarball
        - publish-openstack-python-tarball
    release:
      jobs:
        - publish-openstack-python-tarball:
            dependencies:
              - publish-openstack-python-tarball
        - legacy-announce-release:
            dependencies:
              - legacy-pypi-both-upload
        - legacy-propose-update-constraints:
            dependencies:
              - legacy-pypi-both-upload
        - legacy-pypi-both-upload:
            dependencies:
              - publish-openstack-python-tarball
        - publish-openstack-python-tarball
